Overlapping slider documentation
viivue/overlapping-slider pull request #1
Opened 2022-09-29 10:06 UTC by vuquangpham

Add documentation for Overlapping Slider

2022-10-05 07:11 UTC, vuquangpham commented on README.md
> +### Attribute options
It's a redundant note. I have removed it.

2022-10-05 07:11 UTC, vuquangpham commented on README.md
> +<div data-news-overlapping-slider>
I want to show that we can initialize Overlapping Slider with other data attribute names.

2022-10-05 10:49 UTC, phucbm requested changes
Please check my comments. Thanks.

2022-10-05 10:49 UTC, phucbm commented on README.md
> +| `onChange: (data,el) => {}` | When you call this event, your Overlapping Slider will re-initialize with new options. |
> Trigger after turning off the autoplay setting.
1. When talking about an event, the verb "fire" would be more accurate than "trigger".
2. I can't find anything in common between `onChange` and `re-initialize with new options`.

2022-10-05 10:49 UTC, phucbm commented on README.md
> +| `data-overlapping-slider`   | `data-overlapping-slider="slider-1"` | Pass an specific id for each slider        |
Did you forget this one?

2022-10-05 10:49 UTC, phucbm commented on README.md
> +    <!-- Slider 1 -->
Should you read the number 2 one more time? @vuquangpham

2022-10-07 04:26 UTC, vuquangpham commented on README.md
> +| `data-overlapping-slider`   | `data-overlapping-slider="slider-1"` | Pass an specific id for each slider        |
I have moved it to the top (after the initialize section). Please check it again!

2022-10-07 08:55 UTC, phucbm approved these changes

2022-10-07 08:56 UTC, merged