Add PauseOnHover for autoplay feature
viivue/overlapping-slider pull request #5
Opened 2022-10-18 07:51 UTC by vuquangpham

### Pause On Hover

I have added a little bit of code for the autoplay feature.

With that code, we can control the autoplay feature by hovering over it. You can turn on this option by passing an option `pauseOnHover` through HTML attribute or Javascript object. And when the option `pauseOnHover` is false, I also removed the event listener for optimizing performance.

2022-10-18 10:12 UTC, phucbm requested changes
Please check my comments.

2022-10-18 10:12 UTC, phucbm commented on src/_index.js
> +            this.options.pauseOnHover = isPauseOnHover === "true";
Whenever the attribute for `pauseOnHover` appear in the wrapper element, we will have `pauseOnHover: true`. 

Don't care what the value is. 

This is just the same with the `swipe` option which you might have had a look already, haven't you?

2022-10-18 10:12 UTC, phucbm commented on web/html/home.html
> +        <button data-select="register-poh" data-id="slider-3" class="btn">Add PauseOnHover</button>
There should be only one clickable button at a time. You can either use `.disabled` class (see Pause and Play button) or display none/block as we also don't have so much spacing here to have so many buttons.

2022-10-18 11:14 UTC, vuquangpham commented
I have fixed it. Please check again!

2022-10-19 03:22 UTC, phucbm approved these changes

2022-10-19 03:23 UTC, merged